/**
 * config/mockData.js
 * 50+ real Indian credit cards, 18 banks, 12 loans, 14 FDs.
 * Used as fallback when PostgreSQL is not connected.
 * Also used by the seed script to populate the database.
 */

const MOCK_BANKS = [
    { id: 1, name: 'HDFC Bank', bank_type: 'private', established: 1994, headquarters: 'Mumbai', website: 'https://www.hdfcbank.com' },
    { id: 2, name: 'SBI', bank_type: 'public', established: 1955, headquarters: 'Mumbai', website: 'https://sbi.co.in' },
    { id: 3, name: 'ICICI Bank', bank_type: 'private', established: 1994, headquarters: 'Mumbai', website: 'https://www.icicibank.com' },
    { id: 4, name: 'Axis Bank', bank_type: 'private', established: 1993, headquarters: 'Mumbai', website: 'https://www.axisbank.com' },
    { id: 5, name: 'Kotak Mahindra Bank', bank_type: 'private', established: 2003, headquarters: 'Mumbai', website: 'https://www.kotak.com' },
    { id: 6, name: 'YES Bank', bank_type: 'private', established: 2004, headquarters: 'Mumbai', website: 'https://www.yesbank.in' },
    { id: 7, name: 'IDFC First Bank', bank_type: 'private', established: 2015, headquarters: 'Mumbai', website: 'https://www.idfcfirstbank.com' },
    { id: 8, name: 'IndusInd Bank', bank_type: 'private', established: 1994, headquarters: 'Pune', website: 'https://www.indusind.com' },
    { id: 9, name: 'RBL Bank', bank_type: 'private', established: 1943, headquarters: 'Mumbai', website: 'https://www.rblbank.com' },
    { id: 10, name: 'Standard Chartered', bank_type: 'foreign', established: 1858, headquarters: 'Mumbai', website: 'https://www.sc.com/in' },
    { id: 11, name: 'American Express', bank_type: 'foreign', established: 1850, headquarters: 'Gurugram', website: 'https://www.americanexpress.com/in' },
    { id: 12, name: 'HSBC India', bank_type: 'foreign', established: 1853, headquarters: 'Mumbai', website: 'https://www.hsbc.co.in' },
    { id: 13, name: 'Punjab National Bank', bank_type: 'public', established: 1894, headquarters: 'New Delhi', website: 'https://www.pnbindia.in' },
    { id: 14, name: 'Bank of Baroda', bank_type: 'public', established: 1908, headquarters: 'Vadodara', website: 'https://www.bankofbaroda.in' },
    { id: 15, name: 'Canara Bank', bank_type: 'public', established: 1906, headquarters: 'Bengaluru', website: 'https://canarabank.com' },
    { id: 16, name: 'AU Small Finance Bank', bank_type: 'small_finance', established: 2017, headquarters: 'Jaipur', website: 'https://www.aubank.in' },
    { id: 17, name: 'Shriram Finance', bank_type: 'nbfc', established: 1979, headquarters: 'Chennai', website: 'https://www.shriramfinance.in' },
    { id: 18, name: 'Utkarsh Small Finance Bank', bank_type: 'small_finance', established: 2017, headquarters: 'Varanasi', website: 'https://www.utkarsh.bank' },
];

const MOCK_CREDIT_CARDS = [
    /* ── HDFC Bank ── */
    { id: 1, bank_id: 1, bank_name: 'HDFC Bank', card_name: 'Regalia Gold', annual_fee: 2500, joining_fee: 2500, interest_rate: 43.2, cashback: 0, rewards_type: 'travel', rewards_description: '5X rewards on travel & dining', min_income: 100000, rating: 4.7, lounge_access: true, network: 'Visa', features: ['5X reward points on travel', '12 domestic lounge visits/year', 'Complimentary airport lounge', 'Movie ticket offers'], apply_url: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card', is_active: true },
    { id: 2, bank_id: 1, bank_name: 'HDFC Bank', card_name: 'Millennia', annual_fee: 1000, joining_fee: 1000, interest_rate: 43.2, cashback: 5, rewards_type: 'cashback', rewards_description: '5% cashback on Amazon, Flipkart, Myntra', min_income: 35000, rating: 4.4, lounge_access: false, network: 'Mastercard', features: ['5% cashback on top platforms', '2.5% on wallet/PayZapp', 'Annual fee waiver on ₹1L spend', 'CashPoints'], apply_url: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card', is_active: true },
    { id: 3, bank_id: 1, bank_name: 'HDFC Bank', card_name: 'Diners Club Black', annual_fee: 10000, joining_fee: 10000, interest_rate: 39.6, cashback: 0, rewards_type: 'travel', rewards_description: '10X rewards on Swiggy, Zomato, flights', min_income: 300000, rating: 4.8, lounge_access: true, network: 'Diners', features: ['Unlimited airport lounge', '10X rewards on select brands', 'Golf privileges', 'Concierge service'], apply_url: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-club-black', is_active: true },
    { id: 4, bank_id: 1, bank_name: 'HDFC Bank', card_name: 'MoneyBack+', annual_fee: 500, joining_fee: 500, interest_rate: 43.2, cashback: 2, rewards_type: 'cashback', rewards_description: '10X cashpoints on Amazon & BigBasket', min_income: 20000, rating: 4.2, lounge_access: false, network: 'Mastercard', features: ['10X CashPoints on Amazon', '2X on Flipkart', 'Fee waiver on ₹50K spend', 'EMI on purchases'], apply_url: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/moneyback-plus-credit-card', is_active: true },
    { id: 5, bank_id: 1, bank_name: 'HDFC Bank', card_name: 'Tata Neu Infinity', annual_fee: 1499, joining_fee: 1499, interest_rate: 43.2, cashback: 5, rewards_type: 'shopping', rewards_description: '5% NeuCoins on Tata brands', min_income: 50000, rating: 4.3, lounge_access: false, network: 'Rupay', features: ['5% NeuCoins on Tata Neu app', '1.5% on other spends', 'Fuel surcharge waiver', 'Air accident cover'], apply_url: 'https://www.hdfcbank.com', is_active: true },

    /* ── SBI ── */
    { id: 6, bank_id: 2, bank_name: 'SBI', card_name: 'SimplyCLICK', annual_fee: 499, joining_fee: 499, interest_rate: 42.0, cashback: 1.25, rewards_type: 'shopping', rewards_description: '10X rewards on Amazon, Cleartrip & more', min_income: 20000, rating: 4.3, lounge_access: false, network: 'Visa', features: ['10X rewards on partnered sites', '1.25% cashback', 'Fee waiver on ₹1L spend', 'Contactless payments'], apply_url: 'https://www.sbicard.com/en/personal/credit-cards/shopping/sbi-card-simply-click.page', is_active: true },
    { id: 7, bank_id: 2, bank_name: 'SBI', card_name: 'BPCL Octane', annual_fee: 1499, joining_fee: 1499, interest_rate: 42.0, cashback: 7.25, rewards_type: 'fuel', rewards_description: '7.25% value back on BPCL fuel', min_income: 25000, rating: 4.5, lounge_access: false, network: 'Visa', features: ['7.25% value back on BPCL', 'Surcharge waiver on BPCL', 'Welcome benefits on activation', 'Fuel benefits'], apply_url: 'https://www.sbicard.com/en/personal/credit-cards/petro/bpcl-sbi-card-octane.page', is_active: true },
    { id: 8, bank_id: 2, bank_name: 'SBI', card_name: 'SimplySAVE', annual_fee: 499, joining_fee: 499, interest_rate: 42.0, cashback: 0, rewards_type: 'general', rewards_description: '10X reward points on groceries & dining', min_income: 15000, rating: 4.0, lounge_access: false, network: 'Visa', features: ['10X reward points on select categories', 'Fuel surcharge waiver', 'Contactless payment', 'EMI facility'], apply_url: 'https://www.sbicard.com', is_active: true },
    { id: 9, bank_id: 2, bank_name: 'SBI', card_name: 'Elite', annual_fee: 4999, joining_fee: 4999, interest_rate: 40.2, cashback: 0, rewards_type: 'travel', rewards_description: '5X rewards on dining, grocery, dept stores', min_income: 100000, rating: 4.5, lounge_access: true, network: 'Mastercard', features: ['8 domestic + 4 international lounge/year', '5X reward points', 'Movie vouchers worth ₹6K', 'Emergency card replacement'], apply_url: 'https://www.sbicard.com/en/personal/credit-cards/travel/sbi-card-elite.page', is_active: true },
    { id: 10, bank_id: 2, bank_name: 'SBI', card_name: 'Prime', annual_fee: 2999, joining_fee: 2999, interest_rate: 40.2, cashback: 0, rewards_type: 'shopping', rewards_description: '10X rewards on Big Basket, Ola, Zomato', min_income: 60000, rating: 4.4, lounge_access: true, network: 'Mastercard', features: ['10X rewards on top brands', '8 domestic lounge visits', 'Club Vistara Silver status', 'Milestone benefits'], apply_url: 'https://www.sbicard.com/en/personal/credit-cards/rewards/sbi-card-prime.page', is_active: true },

    /* ── ICICI Bank ── */
    { id: 11, bank_id: 3, bank_name: 'ICICI Bank', card_name: 'Amazon Pay ICICI', annual_fee: 0, joining_fee: 0, interest_rate: 40.8, cashback: 2, rewards_type: 'cashback', rewards_description: '5% on Amazon for Prime; 2% non-Prime', min_income: 25000, rating: 4.6, lounge_access: false, network: 'Visa', features: ['5% cashback on Amazon (Prime)', '2% on Amazon (non-Prime)', '1% on other spends', 'No annual fee'], apply_url: 'https://www.icicibank.com/personal-banking/cards/consumer-credit-card/amazon-pay-credit-card', is_active: true },
    { id: 12, bank_id: 3, bank_name: 'ICICI Bank', card_name: 'Coral Credit Card', annual_fee: 500, joining_fee: 500, interest_rate: 40.8, cashback: 0, rewards_type: 'general', rewards_description: '2 PAYBACK points per ₹100 spent', min_income: 25000, rating: 4.0, lounge_access: false, network: 'Visa', features: ['2 PAYBACK points/₹100', 'Movie discounts on Bookmyshow', 'Fuel surcharge waiver', 'Contactless payments'], apply_url: 'https://www.icicibank.com/personal-banking/cards/consumer-credit-card/coral-credit-card', is_active: true },
    { id: 13, bank_id: 3, bank_name: 'ICICI Bank', card_name: 'Sapphiro Credit Card', annual_fee: 3500, joining_fee: 3500, interest_rate: 40.8, cashback: 0, rewards_type: 'travel', rewards_description: '4 PAYBACK points per ₹100 on travel', min_income: 100000, rating: 4.4, lounge_access: true, network: 'Amex', features: ['4X PAYBACK on travel', 'Spa access at airport', 'Club Vistara Silver', 'Domestic + intl lounge'], apply_url: 'https://www.icicibank.com/personal-banking/cards/consumer-credit-card/sapphiro', is_active: true },
    { id: 14, bank_id: 3, bank_name: 'ICICI Bank', card_name: 'MakeMyTrip ICICI', annual_fee: 0, joining_fee: 0, interest_rate: 42.0, cashback: 0, rewards_type: 'travel', rewards_description: '1.5% myCash on MMT, 1% on all spends', min_income: 25000, rating: 4.2, lounge_access: false, network: 'Mastercard', features: ['1.5% myCash on MakeMyTrip', '1% on all spends', 'Biz card benefits', 'No annual fee'], apply_url: 'https://www.icicibank.com', is_active: true },

    /* ── Axis Bank ── */
    { id: 15, bank_id: 4, bank_name: 'Axis Bank', card_name: 'ACE Credit Card', annual_fee: 499, joining_fee: 499, interest_rate: 43.98, cashback: 2, rewards_type: 'cashback', rewards_description: '2% flat cashback on all spends', min_income: 15000, rating: 4.5, lounge_access: false, network: 'Visa', features: ['2% cashback on all transactions', '5% on utility bills via GPay', 'Fee waiver on ₹2L spend', 'EDGE rewards'], apply_url: 'https://www.axisbank.com/retail/cards/credit-card/ace-credit-card', is_active: true },
    { id: 16, bank_id: 4, bank_name: 'Axis Bank', card_name: 'Reserve Credit Card', annual_fee: 50000, joining_fee: 50000, interest_rate: 39.6, cashback: 0, rewards_type: 'travel', rewards_description: '15 EDGE reward points per ₹200 spent', min_income: 500000, rating: 4.8, lounge_access: true, network: 'Visa', features: ['Unlimited Priority Pass lounge', '15 EDGE points/₹200', 'Dedicated relationship manager', 'Concierge'], apply_url: 'https://www.axisbank.com/retail/cards/credit-card/axis-bank-reserve', is_active: true },
    { id: 17, bank_id: 4, bank_name: 'Axis Bank', card_name: 'Flipkart Axis Bank', annual_fee: 500, joining_fee: 500, interest_rate: 52.86, cashback: 5, rewards_type: 'cashback', rewards_description: '5% cashback on Flipkart & Myntra', min_income: 20000, rating: 4.3, lounge_access: false, network: 'Mastercard', features: ['5% unlimited cashback on Flipkart', '4% on preferred merchants', '1.5% on others', 'Fee waiver on ₹2L spend'], apply_url: 'https://www.axisbank.com/retail/cards/credit-card/flipkart-axis-bank-credit-card', is_active: true },
    { id: 18, bank_id: 4, bank_name: 'Axis Bank', card_name: 'My Zone', annual_fee: 500, joining_fee: 500, interest_rate: 43.98, cashback: 0, rewards_type: 'dining', rewards_description: '25% off on Swiggy, Zomato & restaurants', min_income: 20000, rating: 4.1, lounge_access: false, network: 'Mastercard', features: ['25% off on Swiggy/Zomato', 'Buy 1 Get 1 on Paytm movies', 'EDGE reward points', 'Dining privileges'], apply_url: 'https://www.axisbank.com/retail/cards/credit-card/my-zone-credit-card', is_active: true },

    /* ── Kotak Mahindra ── */
    { id: 19, bank_id: 5, bank_name: 'Kotak Mahindra Bank', card_name: '811 #DreamDifferent', annual_fee: 0, joining_fee: 0, interest_rate: 44.0, cashback: 2, rewards_type: 'general', rewards_description: '2 reward points per ₹100 spent', min_income: 15000, rating: 4.0, lounge_access: false, network: 'Visa', features: ['No annual fee', '2 reward points/₹100', 'Fuel surcharge waiver', 'Online shopping discounts'], apply_url: 'https://www.kotak.com/en/personal-banking/cards/credit-cards/kotak-811-dreamdifferent-credit-card.html', is_active: true },
    { id: 20, bank_id: 5, bank_name: 'Kotak Mahindra Bank', card_name: 'Royale Signature', annual_fee: 1500, joining_fee: 1500, interest_rate: 42.0, cashback: 0, rewards_type: 'travel', rewards_description: '4 reward points per ₹150 on travel', min_income: 50000, rating: 4.2, lounge_access: true, network: 'Visa', features: ['8 domestic lounge visits/year', '4X rewards on travel', 'Dining discounts', 'Milestone rewards'], apply_url: 'https://www.kotak.com', is_active: true },
    { id: 21, bank_id: 5, bank_name: 'Kotak Mahindra Bank', card_name: 'PVR Kotak Platinum', annual_fee: 2500, joining_fee: 2500, interest_rate: 42.0, cashback: 0, rewards_type: 'shopping', rewards_description: '4 free PVR tickets/month worth ₹1200', min_income: 50000, rating: 4.1, lounge_access: false, network: 'Visa', features: ['4 free PVR tickets/month', '25% off on F&B', 'Milestone rewards', 'Welcome bonus'], apply_url: 'https://www.kotak.com', is_active: true },

    /* ── YES Bank ── */
    { id: 22, bank_id: 6, bank_name: 'YES Bank', card_name: 'Marquee', annual_fee: 9999, joining_fee: 9999, interest_rate: 39.6, cashback: 0, rewards_type: 'travel', rewards_description: '24 lounge visits/year; 10X on travel', min_income: 300000, rating: 4.5, lounge_access: true, network: 'Mastercard', features: ['24 domestic + intl lounge visits', '10X reward on travel', 'Concierge', 'Golf privileges'], apply_url: 'https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards', is_active: true },
    { id: 23, bank_id: 6, bank_name: 'YES Bank', card_name: 'Prosperity Edge', annual_fee: 399, joining_fee: 399, interest_rate: 42.0, cashback: 3, rewards_type: 'cashback', rewards_description: '3% cashback on all online spends', min_income: 20000, rating: 4.0, lounge_access: false, network: 'Visa', features: ['3% cashback online', '1.5% on offline', 'Fee waiver on ₹1.5L', 'Fuel surcharge waiver'], apply_url: 'https://www.yesbank.in', is_active: true },

    /* ── IDFC First Bank ── */
    { id: 24, bank_id: 7, bank_name: 'IDFC First Bank', card_name: 'Wealth Credit Card', annual_fee: 0, joining_fee: 0, interest_rate: 9.0, cashback: 0, rewards_type: 'general', rewards_description: '10X rewards on first ₹20K/month; 2.5X after', min_income: 40000, rating: 4.6, lounge_access: true, network: 'Visa', features: ['10X rewards (first ₹20K)', 'No interest on EMI', '4 lounge visits/quarter', 'Waived FX markup'], apply_url: 'https://www.idfcfirstbank.com/credit-card/wealth-credit-card', is_active: true },
    { id: 25, bank_id: 7, bank_name: 'IDFC First Bank', card_name: 'Classic Credit Card', annual_fee: 0, joining_fee: 0, interest_rate: 9.0, cashback: 0, rewards_type: 'general', rewards_description: '10X rewards on first ₹20K/month', min_income: 20000, rating: 4.4, lounge_access: false, network: 'Visa', features: ['10X rewards', 'No annual fee forever', '1.5% fuel surcharge waiver', '0% FX fee'], apply_url: 'https://www.idfcfirstbank.com', is_active: true },
    { id: 26, bank_id: 7, bank_name: 'IDFC First Bank', card_name: 'Select Credit Card', annual_fee: 0, joining_fee: 0, interest_rate: 9.0, cashback: 0, rewards_type: 'shopping', rewards_description: '10X rewards, 25% off on Swiggy, Zomato', min_income: 30000, rating: 4.5, lounge_access: false, network: 'Visa', features: ['10X rewards on select shops', '25% off on Swiggy', 'Zero annual fee', 'Fuel surcharge waiver'], apply_url: 'https://www.idfcfirstbank.com', is_active: true },

    /* ── IndusInd Bank ── */
    { id: 27, bank_id: 8, bank_name: 'IndusInd Bank', card_name: 'Legend Credit Card', annual_fee: 9999, joining_fee: 9999, interest_rate: 42.6, cashback: 0, rewards_type: 'travel', rewards_description: 'Unlimited airport lounge; 2.5 points/₹100', min_income: 200000, rating: 4.6, lounge_access: true, network: 'Visa', features: ['Unlimited domestic lounge', '6 intl Priority Pass lounge', 'Concierge service', 'Foreign currency earn bonus'], apply_url: 'https://www.indusind.com/in/en/personal/cards/credit-cards/indusind-bank-legend-credit-card.html', is_active: true },
    { id: 28, bank_id: 8, bank_name: 'IndusInd Bank', card_name: 'EazyDiner IndusInd', annual_fee: 1999, joining_fee: 1999, interest_rate: 43.2, cashback: 0, rewards_type: 'dining', rewards_description: '20% instant discount at 2000+ restaurants', min_income: 40000, rating: 4.4, lounge_access: false, network: 'Mastercard', features: ['20% off at EazyDiner restaurants', '3X rewards on dining', 'Movie discounts', 'Fuel waiver'], apply_url: 'https://www.indusind.com', is_active: true },
    { id: 29, bank_id: 8, bank_name: 'IndusInd Bank', card_name: 'Platinum Aura Edge', annual_fee: 0, joining_fee: 0, interest_rate: 42.5, cashback: 0, rewards_type: 'fuel', rewards_description: '1.5% fuel surcharge waiver', min_income: 25000, rating: 4.0, lounge_access: false, network: 'Visa', features: ['1% fuel surcharge waiver', 'Reward points every spend', 'Dining discounts', 'VISA offers'], apply_url: 'https://www.indusind.com/in/en/personal/cards/credit-cards.html', is_active: true },

    /* ── RBL Bank ── */
    { id: 30, bank_id: 9, bank_name: 'RBL Bank', card_name: 'Shoprite', annual_fee: 0, joining_fee: 0, interest_rate: 43.2, cashback: 5, rewards_type: 'shopping', rewards_description: '5% cashback on groceries & utility bills', min_income: 20000, rating: 3.9, lounge_access: false, network: 'Mastercard', features: ['5% cashback on groceries', '10% on select merchants', 'No annual fee', 'Contactless'], apply_url: 'https://www.rblbank.com/credit-cards', is_active: true },
    { id: 31, bank_id: 9, bank_name: 'RBL Bank', card_name: 'Popcorn', annual_fee: 0, joining_fee: 0, interest_rate: 43.2, cashback: 0, rewards_type: 'dining', rewards_description: '10% cashback on Zomato & Swiggy', min_income: 20000, rating: 3.8, lounge_access: false, network: 'Mastercard', features: ['10% cashback on food delivery', '2% on dining', 'No annual fee', 'FuelSafe waiver'], apply_url: 'https://www.rblbank.com', is_active: true },

    /* ── Standard Chartered ── */
    { id: 32, bank_id: 10, bank_name: 'Standard Chartered', card_name: 'Platinum Rewards', annual_fee: 0, joining_fee: 0, interest_rate: 41.5, cashback: 0, rewards_type: 'shopping', rewards_description: '5 reward points per ₹150 on dining & fuel', min_income: 25000, rating: 4.1, lounge_access: false, network: 'Visa', features: ['5X rewards on dining & fuel', '1X on all others', 'Fuel surcharge waiver', 'Movie discounts'], apply_url: 'https://www.sc.com/in/credit-cards/', is_active: true },
    { id: 33, bank_id: 10, bank_name: 'Standard Chartered', card_name: 'Ultimate', annual_fee: 5000, joining_fee: 5000, interest_rate: 39.0, cashback: 0, rewards_type: 'travel', rewards_description: '3 reward points per ₹150; unlimited lounge', min_income: 150000, rating: 4.5, lounge_access: true, network: 'Mastercard', features: ['Unlimited Priority Pass lounge', '3X reward points', 'No FX fee', 'Travel insurance cover'], apply_url: 'https://www.sc.com/in/credit-cards/', is_active: true },
    { id: 34, bank_id: 10, bank_name: 'Standard Chartered', card_name: 'Smart Credit Card', annual_fee: 499, joining_fee: 499, interest_rate: 15.0, cashback: 1, rewards_type: 'cashback', rewards_description: '1.5% cashback; 6-month 0% EMI', min_income: 25000, rating: 4.2, lounge_access: false, network: 'Mastercard', features: ['1.5% cashback', '6-month interest-free EMI', 'Low interest rate', 'Bill payment rewards'], apply_url: 'https://www.sc.com/in/', is_active: true },

    /* ── American Express ── */
    { id: 35, bank_id: 11, bank_name: 'American Express', card_name: 'Membership Rewards Gold', annual_fee: 1000, joining_fee: 1000, interest_rate: 42.0, cashback: 0, rewards_type: 'travel', rewards_description: '1 MR point per ₹50; 18X on selected brands', min_income: 40000, rating: 4.4, lounge_access: false, network: 'Amex', features: ['Membership Rewards points', '18X on AMEX Travel portal', 'Taj hotels benefits', 'Dining discounts'], apply_url: 'https://www.americanexpress.com/in/credit-cards/', is_active: true },
    { id: 36, bank_id: 11, bank_name: 'American Express', card_name: 'Plat Travel', annual_fee: 3500, joining_fee: 3500, interest_rate: 42.0, cashback: 0, rewards_type: 'travel', rewards_description: '5000 bonus MR on annual ₹1.90L spend', min_income: 100000, rating: 4.5, lounge_access: true, network: 'Amex', features: ['5000 bonus MR points milestone', 'Taj InnerCircle Silver', 'Club Vistara Silver', 'Lounge access'], apply_url: 'https://www.americanexpress.com/in/credit-cards/', is_active: true },

    /* ── HSBC India ── */
    { id: 37, bank_id: 12, bank_name: 'HSBC India', card_name: 'Cashback Card', annual_fee: 750, joining_fee: 0, interest_rate: 40.8, cashback: 1.5, rewards_type: 'cashback', rewards_description: '1.5% cashback on all online spends', min_income: 25000, rating: 4.2, lounge_access: false, network: 'Visa', features: ['1.5% cashback on all online', 'Joining fee waived', 'Welcome cashback', 'Fuel surcharge waiver'], apply_url: 'https://www.hsbc.co.in/credit-cards/', is_active: true },
    { id: 38, bank_id: 12, bank_name: 'HSBC India', card_name: 'Visa Platinum', annual_fee: 0, joining_fee: 0, interest_rate: 40.8, cashback: 0, rewards_type: 'general', rewards_description: '2 reward points per ₹150 spent', min_income: 20000, rating: 3.9, lounge_access: false, network: 'Visa', features: ['2 reward points/₹150', 'Fuel surcharge waiver', 'No annual fee', 'Movie deals'], apply_url: 'https://www.hsbc.co.in/credit-cards/', is_active: true },

    /* ── PNB ── */
    { id: 39, bank_id: 13, bank_name: 'Punjab National Bank', card_name: 'RuPay Platinum', annual_fee: 299, joining_fee: 299, interest_rate: 38.4, cashback: 0, rewards_type: 'general', rewards_description: 'Reward points on every purchase', min_income: 15000, rating: 3.8, lounge_access: false, network: 'Rupay', features: ['Reward points on all spends', 'Fuel surcharge waiver', 'Accidental insurance', 'Online shopping discounts'], apply_url: 'https://www.pnbindia.in', is_active: true },

    /* ── Bank of Baroda ── */
    { id: 40, bank_id: 14, bank_name: 'Bank of Baroda', card_name: 'ETERNA', annual_fee: 2499, joining_fee: 2499, interest_rate: 39.0, cashback: 0, rewards_type: 'travel', rewards_description: '12 reward points per ₹100 spent on travel', min_income: 50000, rating: 4.0, lounge_access: true, network: 'Visa', features: ['12X reward on travel', '8 domestic lounge visits', 'Visa Signature benefits', 'Fuel surcharge waiver'], apply_url: 'https://www.bankofbaroda.in', is_active: true },
    { id: 41, bank_id: 14, bank_name: 'Bank of Baroda', card_name: 'SELECT', annual_fee: 750, joining_fee: 750, interest_rate: 42.0, cashback: 0, rewards_type: 'general', rewards_description: '2 reward points per ₹100 on all spends', min_income: 25000, rating: 3.9, lounge_access: false, network: 'Mastercard', features: ['2X reward points', 'Fuel surcharge waiver', 'Movie offers', 'Dining discounts'], apply_url: 'https://www.bankofbaroda.in', is_active: true },

    /* ── Canara Bank ── */
    { id: 42, bank_id: 15, bank_name: 'Canara Bank', card_name: 'RuPay Platinum', annual_fee: 0, joining_fee: 0, interest_rate: 37.2, cashback: 0, rewards_type: 'general', rewards_description: 'Reward points on all spends; dining cashback', min_income: 15000, rating: 3.8, lounge_access: false, network: 'Rupay', features: ['No annual fee', 'Reward points', 'Fuel surcharge waiver', 'Dining offers'], apply_url: 'https://canarabank.com', is_active: true },

    /* ── AU Small Finance Bank ── */
    { id: 43, bank_id: 16, bank_name: 'AU Small Finance Bank', card_name: 'Altura Plus', annual_fee: 499, joining_fee: 499, interest_rate: 43.5, cashback: 1.5, rewards_type: 'cashback', rewards_description: '1.5% cashback on all transactions', min_income: 20000, rating: 4.2, lounge_access: false, network: 'Mastercard', features: ['1.5% cashback on all spends', 'Fuel surcharge waiver', 'Welcome benefits', 'FX markup waiver'], apply_url: 'https://www.aubank.in/credit-cards', is_active: true },
    { id: 44, bank_id: 16, bank_name: 'AU Small Finance Bank', card_name: 'Zenith', annual_fee: 7999, joining_fee: 7999, interest_rate: 41.0, cashback: 0, rewards_type: 'travel', rewards_description: '10X rewards on AU travel; unlimited lounge', min_income: 200000, rating: 4.4, lounge_access: true, network: 'Mastercard', features: ['Unlimited lounge access', '10X rewards on AU travel', 'Concierge', 'Golf privileges'], apply_url: 'https://www.aubank.in/credit-cards', is_active: true },

    /* ── More cards from various banks ── */
    { id: 45, bank_id: 3, bank_name: 'ICICI Bank', card_name: 'Emeralde Credit Card', annual_fee: 12000, joining_fee: 12000, interest_rate: 39.6, cashback: 0, rewards_type: 'travel', rewards_description: '4 PAYBACK points/₹100; unlimited lounge', min_income: 300000, rating: 4.7, lounge_access: true, network: 'Mastercard', features: ['Unlimited domestic + intl lounge', '4X PAYBACK points', 'Golf', 'Concierge service'], apply_url: 'https://www.icicibank.com', is_active: true },
    { id: 46, bank_id: 1, bank_name: 'HDFC Bank', card_name: 'Business MoneyBack', annual_fee: 500, joining_fee: 500, interest_rate: 43.2, cashback: 2, rewards_type: 'cashback', rewards_description: '5% cashback on business expenses', min_income: 50000, rating: 4.1, lounge_access: false, network: 'Mastercard', features: ['5% cashback on business', '2% on office supplies', 'GST invoice for spends', 'Annual fee waiver'], apply_url: 'https://www.hdfcbank.com', is_active: true },
    { id: 47, bank_id: 4, bank_name: 'Axis Bank', card_name: 'Magnus Credit Card', annual_fee: 10000, joining_fee: 10000, interest_rate: 39.6, cashback: 0, rewards_type: 'travel', rewards_description: '12 EDGE Reward points per ₹200 spent', min_income: 200000, rating: 4.7, lounge_access: true, network: 'Mastercard', features: ['Unlimited domestic lounge', '6 intl Priority Pass', '12X EDGE rewards', 'FX fee waiver'], apply_url: 'https://www.axisbank.com/retail/cards/credit-card/axis-bank-magnus', is_active: true },
    { id: 48, bank_id: 5, bank_name: 'Kotak Mahindra Bank', card_name: 'White Reserve', annual_fee: 12500, joining_fee: 12500, interest_rate: 39.6, cashback: 0, rewards_type: 'travel', rewards_description: 'Unlimited lounge; 2 Vistara complimentary tickets', min_income: 300000, rating: 4.7, lounge_access: true, network: 'Visa', features: ['Unlimited lounge access', '2 complimentary Vistara tickets', 'Concierge', 'Golf rounds'], apply_url: 'https://www.kotak.com', is_active: true },
    { id: 49, bank_id: 2, bank_name: 'SBI', card_name: 'Cashback SBI Card', annual_fee: 999, joining_fee: 999, interest_rate: 42.0, cashback: 5, rewards_type: 'cashback', rewards_description: '5% cashback on all online transactions', min_income: 30000, rating: 4.6, lounge_access: false, network: 'Visa', features: ['5% cashback online', '1% cashback offline', 'No redemption fee', 'Annual fee waiver on ₹2L'], apply_url: 'https://www.sbicard.com', is_active: true },
    { id: 50, bank_id: 7, bank_name: 'IDFC First Bank', card_name: 'FIRST Millenia', annual_fee: 0, joining_fee: 0, interest_rate: 9.0, cashback: 0, rewards_type: 'general', rewards_description: '10X rewards on first ₹20K spend per month', min_income: 20000, rating: 4.3, lounge_access: false, network: 'Mastercard', features: ['10X reward points', 'No annual fee', 'Low interest rate', 'Zero fuel surcharge'], apply_url: 'https://www.idfcfirstbank.com', is_active: true },
    { id: 51, bank_id: 8, bank_name: 'IndusInd Bank', card_name: 'Pinnacle Credit Card', annual_fee: 20000, joining_fee: 20000, interest_rate: 39.6, cashback: 0, rewards_type: 'travel', rewards_description: 'Unlimited lounge; 5 reward pts/₹100', min_income: 500000, rating: 4.7, lounge_access: true, network: 'Visa', features: ['Unlimited lounge worldwide', '5X reward points', 'Dedicated RM', 'Concierge 24/7'], apply_url: 'https://www.indusind.com', is_active: true },
    { id: 52, bank_id: 6, bank_name: 'YES Bank', card_name: 'Wellness Plus', annual_fee: 1499, joining_fee: 1499, interest_rate: 42.0, cashback: 0, rewards_type: 'shopping', rewards_description: '5% cashback on health & wellness spends', min_income: 35000, rating: 4.1, lounge_access: false, network: 'Rupay', features: ['5% cashback on pharmacy & health', 'OPD discount', 'Wellness partner benefits', 'Fuel waiver'], apply_url: 'https://www.yesbank.in', is_active: true },
    { id: 53, bank_id: 9, bank_name: 'RBL Bank', card_name: 'Monthly Treats', annual_fee: 0, joining_fee: 0, interest_rate: 43.2, cashback: 0, rewards_type: 'dining', rewards_description: 'Complimentary movie ticket every month', min_income: 20000, rating: 3.7, lounge_access: false, network: 'Mastercard', features: ['1 free movie ticket/month', 'Dining discounts', 'Reward points', 'Fuel waiver'], apply_url: 'https://www.rblbank.com', is_active: true },
    { id: 54, bank_id: 11, bank_name: 'American Express', card_name: 'Platinum Card', annual_fee: 60000, joining_fee: 60000, interest_rate: 42.0, cashback: 0, rewards_type: 'travel', rewards_description: 'Unlimited lounge worldwide; 1 MR/₹50', min_income: 800000, rating: 4.9, lounge_access: true, network: 'Amex', features: ['Unlimited lounge worldwide', 'Fine Dining privileges', 'Hotel status', 'Concierge 24/7'], apply_url: 'https://www.americanexpress.com/in/credit-cards/platinum/', is_active: true },
    { id: 55, bank_id: 16, bank_name: 'AU Small Finance Bank', card_name: 'LIT Credit Card', annual_fee: 0, joining_fee: 0, interest_rate: 43.5, cashback: 2, rewards_type: 'cashback', 'rewards_description': 'Choose your own benefits every quarter', min_income: 25000, rating: 4.3, lounge_access: false, network: 'Rupay', features: ['Choose own benefits quarterly', '2% cashback', 'Zero annual fee', 'Customize your card'], apply_url: 'https://www.aubank.in', is_active: true },
];

const MOCK_LOANS = [
    { id: 1, bank_id: 1, bank_name: 'HDFC Bank', loan_name: 'Personal Loan', loan_type: 'personal', interest_rate: 10.50, processing_fee: 2.50, min_tenure: 12, max_tenure: 60, min_amount: 50000, max_amount: 4000000, min_income: 25000, rating: 4.5, features: ['24-hr disbursal', 'No collateral', 'Flexible tenure'], apply_url: 'https://www.hdfcbank.com/personal/borrow/popular-loans/personal-loan', is_active: true },
    { id: 2, bank_id: 2, bank_name: 'SBI', loan_name: 'Xpress Credit', loan_type: 'personal', interest_rate: 10.30, processing_fee: 1.50, min_tenure: 6, max_tenure: 72, min_amount: 25000, max_amount: 2000000, min_income: 15000, rating: 4.4, features: ['Lowest processing fee', 'Online application', 'No prepayment'], apply_url: 'https://sbi.co.in/web/personal-banking/loans/personal-loans', is_active: true },
    { id: 3, bank_id: 4, bank_name: 'Axis Bank', loan_name: 'Personal Loan', loan_type: 'personal', interest_rate: 10.49, processing_fee: 2.00, min_tenure: 12, max_tenure: 60, min_amount: 50000, max_amount: 4000000, min_income: 15000, rating: 4.3, features: ['Instant approval', 'Documentation minimal', 'Prepayment ok'], apply_url: 'https://www.axisbank.com/retail/loans/personal-loan', is_active: true },
    { id: 4, bank_id: 3, bank_name: 'ICICI Bank', loan_name: 'Personal Loan', loan_type: 'personal', interest_rate: 10.65, processing_fee: 2.25, min_tenure: 12, max_tenure: 60, min_amount: 50000, max_amount: 5000000, min_income: 25000, rating: 4.4, features: ['Balance transfer', 'Online tracking', 'Quick disbursal'], apply_url: 'https://www.icicibank.com/personal-banking/loans/personal-loan', is_active: true },
    { id: 5, bank_id: 7, bank_name: 'IDFC First Bank', loan_name: 'Personal Loan', loan_type: 'personal', interest_rate: 10.49, processing_fee: 1.00, min_tenure: 6, max_tenure: 60, min_amount: 20000, max_amount: 4000000, min_income: 20000, rating: 4.5, features: ['Low processing fee', 'No prepayment penalty', 'Instant app'], apply_url: 'https://www.idfcfirstbank.com', is_active: true },
    { id: 6, bank_id: 2, bank_name: 'SBI', loan_name: 'Home Loan', loan_type: 'home', interest_rate: 8.50, processing_fee: 0.50, min_tenure: 60, max_tenure: 360, min_amount: 1000000, max_amount: 100000000, min_income: 25000, rating: 4.6, features: ['Lowest rates', 'No prepayment charges', '30-year tenure'], apply_url: 'https://sbi.co.in/web/personal-banking/loans/home-loans', is_active: true },
    { id: 7, bank_id: 1, bank_name: 'HDFC Bank', loan_name: 'Home Loan', loan_type: 'home', interest_rate: 8.65, processing_fee: 0.50, min_tenure: 60, max_tenure: 360, min_amount: 1000000, max_amount: 200000000, min_income: 30000, rating: 4.7, features: ['Wide network', 'Online management', 'Part prepayment'], apply_url: 'https://www.hdfc.com/home-loans', is_active: true },
    { id: 8, bank_id: 3, bank_name: 'ICICI Bank', loan_name: 'Home Loan', loan_type: 'home', interest_rate: 8.75, processing_fee: 0.50, min_tenure: 60, max_tenure: 360, min_amount: 1000000, max_amount: 150000000, min_income: 30000, rating: 4.5, features: ['Online process', 'Balance transfer', 'Flexible repayment'], apply_url: 'https://www.icicibank.com/personal-banking/loans/home-loan', is_active: true },
    { id: 9, bank_id: 1, bank_name: 'HDFC Bank', loan_name: 'Car Loan', loan_type: 'car', interest_rate: 8.80, processing_fee: 1.00, min_tenure: 12, max_tenure: 84, min_amount: 100000, max_amount: 15000000, min_income: 20000, rating: 4.5, features: ['90% funding', 'Quick approval', 'EMI tracker'], apply_url: 'https://www.hdfcbank.com/personal/borrow/popular-loans/car-loan', is_active: true },
    { id: 10, bank_id: 2, bank_name: 'SBI', loan_name: 'Car Loan', loan_type: 'car', interest_rate: 8.75, processing_fee: 0.51, min_tenure: 12, max_tenure: 84, min_amount: 100000, max_amount: 10000000, min_income: 20000, rating: 4.4, features: ['No prepayment penalty', 'Used cars too', 'Online application'], apply_url: 'https://sbi.co.in/web/personal-banking/loans/auto-loans', is_active: true },
    { id: 11, bank_id: 3, bank_name: 'ICICI Bank', loan_name: 'Education Loan', loan_type: 'education', interest_rate: 10.25, processing_fee: 0, min_tenure: 12, max_tenure: 180, min_amount: 50000, max_amount: 10000000, min_income: 0, rating: 4.3, features: ['No collateral up to ₹7.5L', 'Moratorium period', 'Tax benefit'], apply_url: 'https://www.icicibank.com/personal-banking/loans/education-loan', is_active: true },
    { id: 12, bank_id: 2, bank_name: 'SBI', loan_name: 'Scholar Loan', loan_type: 'education', interest_rate: 8.15, processing_fee: 0, min_tenure: 12, max_tenure: 180, min_amount: 20000, max_amount: 15000000, min_income: 0, rating: 4.5, features: ['Lowest rates', 'IIM/IIT concession', 'Simple interest during study'], apply_url: 'https://sbi.co.in/web/personal-banking/loans/education-loans', is_active: true },
];

const MOCK_FDS = [
    { id: 1, bank_id: 2, bank_name: 'SBI', scheme_name: 'SBI Fixed Deposit', bank_type: 'public', interest_rate: 6.80, senior_citizen_rate: 7.30, min_tenure: 7, max_tenure: 3650, min_amount: 1000, compounding_frequency: 'quarterly', rating: 4.5, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://sbi.co.in/web/personal-banking/investments-deposits/deposits/term-deposits/fixed-deposit', is_active: true },
    { id: 2, bank_id: 1, bank_name: 'HDFC Bank', scheme_name: 'HDFC Fixed Deposit', bank_type: 'private', interest_rate: 7.10, senior_citizen_rate: 7.60, min_tenure: 7, max_tenure: 3650, min_amount: 5000, compounding_frequency: 'quarterly', rating: 4.7, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.hdfcbank.com/personal/save/deposits/fixed-deposit', is_active: true },
    { id: 3, bank_id: 3, bank_name: 'ICICI Bank', scheme_name: 'ICICI Fixed Deposit', bank_type: 'private', interest_rate: 7.10, senior_citizen_rate: 7.60, min_tenure: 7, max_tenure: 3650, min_amount: 10000, compounding_frequency: 'quarterly', rating: 4.6, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.icicibank.com/personal-banking/deposits/fixed-deposit', is_active: true },
    { id: 4, bank_id: 4, bank_name: 'Axis Bank', scheme_name: 'Axis Fixed Deposit', bank_type: 'private', interest_rate: 7.10, senior_citizen_rate: 7.60, min_tenure: 7, max_tenure: 3650, min_amount: 5000, compounding_frequency: 'quarterly', rating: 4.5, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.axisbank.com/retail/deposits/fixed-deposit', is_active: true },
    { id: 5, bank_id: 5, bank_name: 'Kotak Mahindra Bank', scheme_name: 'Kotak FD', bank_type: 'private', interest_rate: 7.25, senior_citizen_rate: 7.75, min_tenure: 7, max_tenure: 3650, min_amount: 5000, compounding_frequency: 'quarterly', rating: 4.4, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.kotak.com/en/personal-banking/deposits/term-deposits/fixed-deposit.html', is_active: true },
    { id: 6, bank_id: 13, bank_name: 'Punjab National Bank', scheme_name: 'PNB Fixed Deposit', bank_type: 'public', interest_rate: 6.75, senior_citizen_rate: 7.25, min_tenure: 7, max_tenure: 3650, min_amount: 1000, compounding_frequency: 'quarterly', rating: 4.2, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.pnbindia.in/fixed-deposit.html', is_active: true },
    { id: 7, bank_id: 14, bank_name: 'Bank of Baroda', scheme_name: 'BOB Fixed Deposit', bank_type: 'public', interest_rate: 6.85, senior_citizen_rate: 7.35, min_tenure: 7, max_tenure: 3650, min_amount: 1000, compounding_frequency: 'quarterly', rating: 4.2, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.bankofbaroda.in', is_active: true },
    { id: 8, bank_id: 6, bank_name: 'YES Bank', scheme_name: 'YES Bank FD', bank_type: 'private', interest_rate: 7.75, senior_citizen_rate: 8.25, min_tenure: 7, max_tenure: 3650, min_amount: 10000, compounding_frequency: 'quarterly', rating: 3.8, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.yesbank.in/personal-banking/yes-individual/deposits/fixed-deposits', is_active: true },
    { id: 9, bank_id: 8, bank_name: 'IndusInd Bank', scheme_name: 'IndusInd FD', bank_type: 'private', interest_rate: 7.50, senior_citizen_rate: 8.00, min_tenure: 7, max_tenure: 3650, min_amount: 10000, compounding_frequency: 'quarterly', rating: 4.2, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.indusind.com/in/en/personal/deposits/fixed-deposit.html', is_active: true },
    { id: 10, bank_id: 17, bank_name: 'Shriram Finance', scheme_name: 'Shriram Fixed Deposit', bank_type: 'nbfc', interest_rate: 8.51, senior_citizen_rate: 8.76, min_tenure: 180, max_tenure: 1825, min_amount: 5000, compounding_frequency: 'monthly', rating: 4.0, premature_withdrawal: false, loan_against_fd: true, apply_url: 'https://www.shriramfinance.in/fixed-deposits', is_active: true },
    { id: 11, bank_id: 18, bank_name: 'Utkarsh Small Finance Bank', scheme_name: 'Utkarsh FD', bank_type: 'small_finance', interest_rate: 8.50, senior_citizen_rate: 9.00, min_tenure: 7, max_tenure: 1825, min_amount: 1000, compounding_frequency: 'quarterly', rating: 4.0, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.utkarsh.bank/fixed-deposits', is_active: true },
    { id: 12, bank_id: 15, bank_name: 'Canara Bank', scheme_name: 'Canara Fixed Deposit', bank_type: 'public', interest_rate: 6.80, senior_citizen_rate: 7.30, min_tenure: 7, max_tenure: 3650, min_amount: 1000, compounding_frequency: 'quarterly', rating: 4.1, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://canarabank.com', is_active: true },
    { id: 13, bank_id: 7, bank_name: 'IDFC First Bank', scheme_name: 'IDFC First FD', bank_type: 'private', interest_rate: 7.75, senior_citizen_rate: 8.25, min_tenure: 7, max_tenure: 3650, min_amount: 10000, compounding_frequency: 'quarterly', rating: 4.3, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.idfcfirstbank.com', is_active: true },
    { id: 14, bank_id: 16, bank_name: 'AU Small Finance Bank', scheme_name: 'AU FD', bank_type: 'small_finance', interest_rate: 8.10, senior_citizen_rate: 8.60, min_tenure: 7, max_tenure: 1825, min_amount: 1000, compounding_frequency: 'quarterly', rating: 4.2, premature_withdrawal: true, loan_against_fd: true, apply_url: 'https://www.aubank.in', is_active: true },
];

const MOCK_USERS = [];  // No mock users — auth always requires DB or demo-mode token

module.exports = { MOCK_BANKS, MOCK_CREDIT_CARDS, MOCK_LOANS, MOCK_FDS, MOCK_USERS };
